"""empty message

Revision ID: f7187aa29326
Revises: f8581e1119e8
Create Date: 2025-09-14 13:46:27.563457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7187aa29326'
down_revision = 'f8581e1119e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visited',
    sa.Column('phira_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('phira_id')
    )
    op.drop_table('known_phira_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('known_phira_ids',
    sa.Column('phira_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('phira_id')
    )
    op.drop_table('visited')
    # ### end Alembic commands ###
